include ../makefiles/platforms.mk
include ../user.mk
include ../makefiles/default.mk


main: $(ORDERINGS)




$(DIRORDERINGS)$(FLOAT)/*perm*.o:                          $(DIRORDERINGS)scaleprefix.c

$(DIRORDERINGS)$(FLOAT)/*.o: ../include/ilupackmacros.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/ilupack*.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/namesilupack.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/long_integer.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/f2c.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/blas.h
$(DIRORDERINGS)$(FLOAT)/*.o: ../include/namesblas.h



